-- CRIANDO UMA TABELA CLIENTE

CREATE TABLE CLIENTE
(
CODIGO INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(20),
EMAIL VARCHAR(50)
)
GO

--PROCEDIMENTO DE INSERÇÃO

ALTER PROCEDURE INSERIR_CLIENTES
--	@CODIGO		INT OUTPUT,
	@NOME		VARCHAR(100),
	@TELEFONE	VARCHAR(20),	
	@EMAIL		VARCHAR(50)
	
AS
BEGIN
		INSERT INTO CLIENTES(NOME,TELEFONE,EMAIL)
		VALUES(@NOME, @TELEFONE, @EMAIL)
		
--		SELECT @CODIGO=MAX(CODIGO) FROM CLIENTES
END

--PROCEDIMENTO DE EDIÇÃO(ATUALIAÇÃO)

ALTER PROCEDURE ALTERAR_CLIENTES
	@CODIGO		INT,
	@NOME		VARCHAR(100),
	@TELEFONE	VARCHAR(20),	
	@EMAIL		VARCHAR(50)
	
AS 
BEGIN
		UPDATE CLIENTES 
		SET NOME=@NOME,TELEFONE=@TELEFONE,EMAIL=@EMAIL WHERE CODIGO=@CODIGO			
END

--PROCEDIMENTO DE EXCLUSÃO

ALTER PROCEDURE EXCLUIR_CLIENTE
		@CODIGO		INT
AS
BEGIN
		DELETE FROM CLIENTES WHERE CODIGO=@CODIGO
END

--PRECEDIMENTO PARA SELEÇÃO

 CREATE PROCEDURE SELECIONAR_CLIENTE
    @TIPO   INT,
    @VALOR  VARCHAR(100)
AS
BEGIN
    IF @TIPO = 1
    BEGIN
        IF ISNUMERIC(@VALOR) = 1
        SELECT * FROM CLIENTES WHERE CODIGO = CAST(@VALOR AS INTEGER)
    END
    ELSE
    IF @TIPO = 2
    BEGIN
        SELECT * FROM CLIENTES
WHERE NOME LIKE '%'+@VALOR+'%'
    END
    ELSE
    IF @TIPO = 3
    BEGIN
        SELECT * FROM CLIENTES
WHERE TELEFONE LIKE '%'+@VALOR+'%'
    END
    ELSE
    IF @TIPO = 4
    BEGIN
        SELECT * FROM CLIENTES
WHERE EMAIL LIKE '%'+@VALOR+'%'
    END    
END

CREATE PROCEDURE SELECIONAR_CLIENTES
        @CODIGO INT
        
AS
BEGIN
SELECT * FROM CLIENTES WHERE CODIGO=@CODIGO
END